### ISSUE TITLE
How to execute compensation

### ISSUE THREAD

**Issue by 3cpt** [MassTransit/Sample-Courier#2]
Hello.

I'm trying running the example and reach the Compensate of the Retrive activity. How to?

Thanks

**Comment by 3cpt** [comment]
I understand a Compensation wrongly. I supposed that a compensation is executed to the current Activity, not when the that the compensation by the previous activity.

Anyway, should the example be improved? Or I still thinking wrongly? Can I make Activities only to compensation?

The courier seems very powerful, but the examples should be more expressive.

Thanks a lot guys, and keep the good work.

**Comment by 3cpt** [comment]
Just one more appointment: Can the first activity be compensated?

**Comment by phatboyg** [comment]
You can't compensate the first activity. If it faults, it never recorded anything in the routing slip to be compensated. You can compensate it if it completes and a subsequent activity faults, but not if it's the first and only activity that executes.

**Comment by phatboyg** [comment]
Look at: https://github.com/phatboyg/Demo-Registration

Might be more detailed.

**Comment by 3cpt** [comment]
Let me check it. Thanks a lot.
