### ISSUE TITLE
Update to new version

### ISSUE THREAD

**Issue by ayberkcanturk** [MassTransit/Sample-Courier#6]
This example is using MassTransit 3.5 while the last version is 7.0.2. 

I am trying to figure out implementing courier in my project and as far as I see I need to change a few things like implementing IActivity, instead of Activity in our Activities. Other than this, I see context.Completed is not supporting GetAwaiter() any more so can't use it in async method. But the implementation requires to return a Task so had to use Task factory inside Execute method which doesn't seem a good approach for me:

```
public xxxActivity(IRepository<xxx> xxxRepository)
        {
            _xxxRepository = xxxRepository ?? throw new ArgumentNullException(nameof(xxxRepository));
        }

        public Task<ExecutionResult> Execute(ExecuteContext<IxxxActivityArgs> context)
        {
            return Task.Factory.StartNew(() => context.Completed<IxxxActivityLog>(new
            {
                context.Arguments.UserId, context.Arguments.JobId, context.Arguments.TimeStamp,
                ExecutedTimeStamp = DateTime.UtcNow
            }));
        }
```

Any advice?

Do you have plans for updating this repository with new version?

Thanks.

**Comment by phatboyg** [comment]
There are much better examples of using Courier. Such as https://github.com/MassTransit/Sample-Twitch/tree/master/src/Sample.Components/CourierActivities

I don't have plans to update this sample.

There is also a series of videos on YouTube that cover this sample from creation to where it is presently.

**Comment by ayberkcanturk** [comment]
I have started watching your series and actually subscribed as well. Thank you for your time.
